project:
  type: website
  title: "Analisis GTD"
  output-dir: docs

website:
  navbar:
    right:
      - text: "Python"
        href: index.qmd
      - text: "R"
        href: about.qmd
      - icon: github
        href: "https://github.com/Brandon780"
        aria-label: GitHub
      - icon: linkedin
        href: "https://www.linkedin.com/in/brandonth/"
