project:
  type: website
  title: "Análisis GTD"
  output-dir: docs

website:
  title: "Análisis GTD"
  navbar:
    right:
      - icon: github
        href: "https://github.com/Brandon780"
        aria-label: GitHub
      - icon: linkedin
        href: "https://www.linkedin.com/in/brandonth/"

  sidebar:
    background: "#f8f9fa"
    border: true
    width: 250px
    contents:
      - text: "Python"
        href: index.qmd
      - text: "R"
        href: about.qmd
    collapse-level: 1
    search: true

  page-footer:
    left:
      - text: "© 2025 Brandon Martínez"
    center:
      - text: "Licencia: CC0"
        href: https://creativecommons.org/publicdomain/zero/1.0/
    right:
      - icon: github
        href: "https://github.com/Brandon780"
        aria-label: GitHub

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    toc-location: right
    grid:
      sidebar-width: 250px

execute:
  cache: false
